### ISSUE TITLE
Properly handle Volume of Volumes

### ISSUE THREAD

**Issue by winterborn** [Casvt/Kapowarr#83] opened 2023-07-29 21:38 UTC
**Is your feature request related to a problem? Please describe.**
Properly handle a Volume of Volumes, e.g. [Mighty Morphin Power Rangers](https://comicvine.gamespot.com/mighty-morphin-power-rangers/4050-94128/)

Currently, even if files are present and when scanned, are not properly picked up by Kapowarr or renamed appropriately.

**Describe the solution you'd like**
Unsure what it should look like, whether it make sense for a Volume of Volumes to be named as Issues or Volumes...

**Comment by Casvt** [comment] 2023-07-29 21:44
Duplicate of #23

**Closed by Casvt** 2023-07-29 21:44 UTC
Labels: enhancement
