### ISSUE TITLE
New releases - Add to Monitor

### ISSUE THREAD

**Issue by polomint278** [Casvt/Kapowarr#189] opened 2024-10-13 16:16 UTC
Perhaps a browsable "New releases" section - that scrapes all the new releases from the sources

Then presents them to user for monitoring or not monitoring

Perhaps having a "never ask me again" against certain series or even publishers,
So yoiu only get a list of those you havent been asked before, although this would also need a way of removing from this list in case of a mistake

**Comment by Casvt** [comment] 2024-10-13 17:08
Duplicate of #6

**Closed by Casvt** 2024-10-13 17:08 UTC
Labels: enhancement
