### ISSUE TITLE
[Feature Request] Issue number padding

### ISSUE THREAD

**Issue by Serneum** [Casvt/Kapowarr#70] opened 2023-07-14 14:51 UTC
Many of my existing comics have a naming pattern that involves padded zeroes, which is a preference of mine to help organize them, especially when sometimes the operating system will perform odd ordering, putting `1` near `10`, etc. It would be nice to have a user-specified or a user-selectable option for padding.

An example of this can be found in other apps (screenshot is a dropdown hiding a checkbox to enable the feature):
![image](https://github.com/Casvt/Kapowarr/assets/1091716/bc5a55d7-72d7-4d81-bbef-1bd3c8a7cd84)

**Comment by Casvt** [comment] 2023-07-14 14:59
Duplicate of #31

**Closed by Casvt** 2023-07-14 14:59 UTC
Labels: duplicate, enhancement
