### ISSUE TITLE
Volumes with more than one TPB blacklists the other links

### ISSUE THREAD

**Issue by ItsNoted** [Casvt/Kapowarr#11] opened 2023-04-26 17:17 UTC
Sometimes a volume has more than one TPB. If so, it downloads the first one but then blacklists all the others thinking it is complete with the first TPB. Here is an example CV ID https://comicvine.gamespot.com/new-mutants-by-vita-ayala/4050-138157/

**Comment by Casvt** [comment] 2023-06-26 10:02
Duplicate of #23

**Closed by Casvt** 2023-06-26 10:02 UTC
Labels: bug
