### ISSUE TITLE
Allow Manual Import and Mapping

### ISSUE THREAD

**Issue by Gandalf-the-Blue** [Casvt/Kapowarr#124] opened 2024-01-09 17:35 UTC
**Is your feature request related to a problem? Please describe.**
Sometimes auto import does not work with some issues/ volumes, i.e. it works 95% of the time, but not 100%
Having an additional manual import option where one can map the file to the issue would solve this issue.

**Describe the solution you'd like**
Have a manual import option that opens up a screen similar to sonarr/readarr/lidarr etc. where mapping is possible.

**Additional context**
NA

**Comment by Casvt** [comment] 2024-01-09 17:37
Duplicate of #46.

But what are the scenarios that it doesn't match? Wouldn't mind making that 95% closer to 99%.

**Closed by Casvt** 2024-01-09 17:37 UTC
Labels: enhancement

**Comment by Casvt** [comment] 2024-01-09 21:09
> Absolute Crisis on Infinite Earths

On GC the release is called "[Crisis on Infinite Earths – The Absolute Edition (HC) (2005)](https://getcomics.org/dc/crisis-infinite-earths-absolute-edition-hc/)" which doesn't match the CV title of "Absolute Crisis On Infinite Earths". On top, the issue title is "The Absolute Edition" which also doesn't match. So nothing matches. This would be a good case for manual file matching yes.

> Absolute DC: The New Frontier

This is a hard cover without a release on GC. So I'd have to know what the filename is. But I know that in beta-4 (fixed in my local version already but not released yet), the filename _needs_ to have 'hard cover' (or any version of it) in the filename in order to match. In the next release, issue number 1 or none at all is also allowed.

> Action Comics (2011) - Certain Issues

Without telling me exactly which ones, I can't know. One thing I know though is that beta-4 has a bug where issues for issue 0 get mapped to the issue number with the same number as the volume number. So in the case of this volume, the file for issue 0 get's mapped to issue 2. That has been fixed of course, but you'll still encounter it. If there are any other issues in this volume with problems, you'll have to tell me which ones exactly.

> Daytripper (2011)

Don't see anything wrong with this before I can see the filename. Files only match to a TPB volume like this one when they _don't_ have an issue number in them. So if your file is named `Daytripper Volume 1 Issue 1 The Deluxe Edition`, or something like that, it won't match. But `Daytripper Volume 1 The Deluxe Edition` or `Daytripper Volume 1 TPB` will match.

**Comment by Casvt** [comment] 2024-01-10 11:05
> For Action Comics (2011) - Issue 0 & 20 isn't getting mapped + Issues 31-34 (separate files) get mapped to Issue 1
> The Flash (1987) - Issue 0, 109,110,132,136-141, 80-94 (single issue) - Aren't getting mapped properly.

Seems that all these issues have to do with having 'Part' or 'Chapter' in the issue title. I believe I added handling for that, but I depends on the filename. Could you give an example filename of one of the issues?

**Comment by Casvt** [comment] 2024-01-10 12:55
Kapowarr doesn't care what the file format is when scanning for files. They're two completely different things. The mapping of Issue 0 to Issue {volume_number} is already fixed. Issue 31 being mapped to Issue 1 is because the title of the issue contains 'Chapter 1', which makes Kapowarr think that it's for Issue 1. I believe I added handling for that, but apparently it's not working well yet.

**Comment by Casvt** [comment] 2024-01-10 13:09
Fixed it. The whole problem was that Kapowarr supported 'Chapter' as a keyword similar to 'Issue'. And this would mess up when the title contains the word 'chapter'. However, it's not very common to use 'Chapter' to signify the issue number of a volume, so I just removed support for 'Chapter' being an alternative to 'Issue'. And because of this the problem with 'Chapter' in the title is also resolved. 'c' is still allowed (e.g. 'v2c8' = Volume 2 Issue 8).
