### ISSUE TITLE
Refresh/Scan stuck if cannot find item location until application restarted

### ISSUE THREAD

**Issue by Andrewpaps** [Casvt/Kapowarr#53] opened 2023-06-11 09:00 UTC
**Description of the bug**
Refresh/Scan getting stuck if contents are removed prior to scan and Kapowarr cannot find it. Disables ability to start another rescan and no current function to cancel scan. Only resolved upon restart.

**To Reproduce**
1. Add item
2. Delete folder/contents
3. Attempt Refresh/Scan

**Expected behaviour**
Timeout or other way to continue function if contents not found.

**Comment by rmohns** [comment] 2023-06-27 13:47
I also experience this bug.

**Comment by Casvt** [comment] 2023-07-23 19:55
@Andrewpaps @rmohns Please respond

**Comment by Casvt** [comment] 2023-07-25 11:38
@Andrewpaps @rmohns I'm going to close the issue until one responds

**Comment by Andrewpaps** [comment] 2023-07-25 15:53
Not sure how to describe this any differently to post 1.

If a folder or a folder's contents are removed manually, Kapowarr hitches when trying to do a scan as it is unable to find that folder and unable to continue. This is only fixed by a complete restart and then deleting that volume in Kapowarr before it attempts to scan it again.

If there is code that creates a folder before scanning if it is missing, it is surely not working as intended. No error is thrown, it just gets stuck scanning.

**Comment by Casvt** [comment] 2023-07-28 15:44
This is what I did:

1. I have a volume with a folder and content in it.
2. I do a "Refresh & Scan", the checkmarks pop up for the right issues. Everything is normal up to this point.
3. I delete the volume folder.
4. I do a "Refresh & Scan".
5. Kapowarr creates the missing folder. The checkmarks disappear (logically), but everything was handled fine. No error. The missing folder was created.

So I'm still not able to reproduce. If you haven't yet, please upgrade to v1.0.0-beta-2 and see if the error persists.

**Comment by Casvt** [comment] 2023-08-20 21:10
@Andrewpaps @rmohns reminder to respond

**Closed** 2023-09-24 11:50 UTC
Labels: bug
