### ISSUE TITLE
Search using alt title i.c.o. no results

### ISSUE THREAD

**Issue by Kanoans** [Casvt/Kapowarr#172] opened 2024-08-12 17:14 UTC
**Is your feature request related to a problem? Please describe.**
There are some series where the name on all getcomics files do not match the comicvine name. The largest one is 2000 AD, long running British comic series. Comicvine officially has the name listed as "2000 AD", getcomics has the series under "2000AD" (no space). The issue is that GC isn't wrong, both are accepted titles for the series and even Comicvine uses both titles interchangeably in articles. But for Kapowarr, it just thinks GC doesn't have anything. 

**Describe the solution you'd like**
User defined Alternate series. basically a Fallback. So if it can't find something under the normal volume title (2000 AD), it can then search the backup title that the user has set (2000AD)

**Additional context**

**Comment by Casvt** [comment] 2024-08-12 17:52
I actually encountered this exact thing before. At the time, the solution was to not only search for the title, but also search for alternative titles. The reason I did not implement this is that it would increase the search time significantly. With only one alternative title, it would already double the search time.

What I didn't think about back then was that I could just search normally initially and only if that doesn't give any results, search using alternative titles. This gives normal search times in most cases.

I do not think offering the user to change the (search-)title of the volume is smart; it's probably too confusing and scenario's in which you need this are rare. I think it's better to just use the alternative titles supplied by CV. If it then still doesn't work, then the volume on CV should just be edited to have the extra alternative title.

So to conclude, unless you have a better plan, we'll search normally but if we don't have any search results, we'll search using the alternative titles. That's it.

**Comment by Kanoans** [comment] 2024-08-12 18:39
That's fair, user controlled alternate names could be confusing. I just suggested it for cases were comicvine does not list the necessary alternate series name. For some reason I do not understand), Aliases are one of the things that comicvine does not seem to like to let normal users edit. 

You are probably correct though, that is alot more complexity for kapowarr just to account for a few edge edge cases. 
Thank you for the quick response!

**Comment by Casvt** [comment] 2024-08-12 18:54
Kapowarr relies on GC and CV. There has to be a line drawn somewhere regarding how much we "trust" these services.

We can allow users to add alternative titles themselves, or CV should just improve their metadata by adding common alternative titles.

On GC, the year is sometimes wrong (e.g. 2204 instead of 2024) and I was strongly against adding handling for it. I can write extra code to fix obvious mistakes, or GC just fixes their typos. I still added it because it was happening too often, but I didn't want to because that way we allow erroneous data to stay.

By (rightfully) blaming CV if we need to, the source of the problem is fixed instead of avoiding it.

Users often find such answers hard, because it sounds a lot like "I don't care, let somebody else fix it", but in reality it just means that the source of the problem should be fixed and we should not allow to problem to stay by avoiding it or fixing it ourselves afterwards.

**Closed** 2024-11-07 13:43 UTC
Labels: enhancement

**Comment by Casvt** [comment] 2024-11-07 13:45
Implemented. Requires an Update All or Refresh & Scan once before it works for the volume (alternative title needs to be fetched from CV).

I tested it with 2000 AD and it worked. Seems like someone has added 2000AD as an alternative title in CV so that's great.
