### ISSUE TITLE
Kapowarr loses track of some volumes

### ISSUE THREAD

**Issue by quentinhill** [Casvt/Kapowarr#81] opened 2023-07-28 14:29 UTC
**Description of the bug**

Kapowarr loses track of some scanned issues. I'd say this affects about half of the volumes I've created. The volume is still listed in Kapowarr, it's just empty. Trying to refresh the volume does nothing. The logs say:

    [waitress-0][INFO] Added task: Refresh and scan (1)
    [Task Handler][INFO] Finished task Refresh and Scan

The files are still in the same location that Kapowarr first found them. They have not been moved or deleted.

**To Reproduce**

1. Create a volume, and scan in the issues.
2. ???, come back after a few days
3. About a third to half of scanned volumes are now empty.

**Expected behaviour**

Kapowarr should not lose track of issues/volumes once scanned into the app.

**Version info**

Kapowarr: v1.0.0-beta-2
Python: 3.8.16.final.0
Database: 7
Database path: /app/db/Kapowarr.db
Data folder: /app

**Additional context**

I'm running Kapowarr through Docker on Linux.

**Comment by winterborn** [comment] 2023-07-29 14:42
Mostly TPBs on my end - have double checked and made sure the requested releases are in fact TPBs and still not being scanned properly...

**Comment by Casvt** [comment] 2023-07-29 18:16
Kapowarr says that a TPB release on CV has only one issue: the TPB. Is that the case?

**Comment by winterborn** [comment] 2023-07-30 13:26
It could be due to my older naming conventions prior to beta-2. Am I right in thinking a volume of volumes should still have each file treated as: 

- Mighty Morphin Power Rangers (2016) - Volume 01 - Issue 001
- Mighty Morphin Power Rangers (2016) - Volume 01 - Issue 002
- Mighty Morphin Power Rangers (2016) - Volume 01 - Issue 003

Even though Issue 2 is Volume 2, Issue 3 is Volume 3 etc?

Similarly, I might be missing the point of the setting: _Treat Volume Issues As "No Title"_ - Are you able to explain this in further detail as I'm confused by this...

**Comment by Casvt** [comment] 2023-07-31 10:27
@winterborn 

> Am I right in thinking a volume of volumes should still have each file treated as:

Yes for now that's the right naming.

> Similarly, I might be missing the point of the setting: Treat Volume Issues As "No Title" - Are you able to explain this in further detail as I'm confused by this...

There is a naming format for when issues don't have titles. That way they have nicer names. E.g. `Wonder Woman Volume 2 Issue 3.cbr` instead of `Wonder Woman Volume 2 Issue 3 - Unknown.cbr`.

The option you're talking about determines if issues that are volumes should also be named as if they have no title. E.g. `Wonder Woman Volume 2 Issue 3.cbr` instead of `Wonder Woman Volume 2 Issue 3 - Volume 3.cbr`. Mainly because applications get confused by the fact that there are two volumes mentioned in the filename.

-----------

@quentinhill 

Can you supply the volume (comicvine id or title, volume number and year) and an example of a filename that isn't being detected?

**Comment by Casvt** [comment] 2023-07-31 20:19
@quentinhill 

Regarding "Agent 47: Birth of the Hitman":

The CV id that you supplied leads to the TPB release on CV for the volume. However, the filename that you gave doesn't say that it's a TPB, it says that it's issue 1. Issue 1 of 1 != TPB. So Kapowarr correctly doesn't match the file. If you replace `Issue 1` with `TPB`, it'll match.

Regarding "Elvira Mistress of the Dark Spring Special One-Shot":

To start with, Kapowarr doesn't handle special editions (one-shots and similar) very well. But in this case it doesn't matter. There is only one issue in the volume, so Kapowarr handles it as a TPB release from CV. The filename says that it's issue 1, not TPB, so it doesn't match. Basically the same problem with Agent 47. Now this is a more difficult case because it's not actually a TPB, it's a one-shot. But as I said, Kapowarr doesn't handle such versions very well for now, so it's gives it the same treatment as a TPB.

**Comment by Casvt** [comment] 2023-07-31 20:24
@winterborn 

> Oh and, I do have an instance where one set of files are named correctly, but fails to pick up the final 2 issues within a volume as being there...

Could you supply: 

1. The ComicVine ID of the volume (or otherwise title, year and volume number)
2. The filenames of those two files that _aren't_ being matched
3. The filename of one of the files that _is_ being matched

**Comment by rophel** [comment] 2023-08-04 16:25
Having a similar issue:

1. Added volume Werewolf by Night using K.
https://comicvine.gamespot.com/werewolf-by-night/4050-131352/

2. Got issue 1-3 from GetComics using auto download, kept scene names, i.e. Werewolf by Night 001 (2020) (Digital) (Zone-Empire).

3. Issue 4 refuses to download, downloaded manually from GetComics and moved to directory.

4. None of them are detected as completed, it thinks there are no issues in that volume no matter how many times I rescan.

**Comment by winterborn** [comment] 2023-08-04 16:54
> @winterborn
> 
> > Oh and, I do have an instance where one set of files are named correctly, but fails to pick up the final 2 issues within a volume as being there...
> 
> Could you supply:
> 
> 1. The ComicVine ID of the volume (or otherwise title, year and volume number)
> 2. The filenames of those two files that _aren't_ being matched
> 3. The filename of one of the files that _is_ being matched

Hey, for sure, sorry it has been a busy week - here:

- ComicVine link and ID: [Firefly (2018)](https://comicvine.gamespot.com/firefly/4050-115251/) ID: 4050-115251
- Filenames of two files **not** being matched: `Firefly (2018) - Volume 01 - Issue 035.cbr` & `Firefly (2018) - Volume 01 - Issue 036.cbr`
- Filename of one file that **is** being matched: `Firefly (2018) - Volume 01 - Issue 030.cbr`

**Comment by Casvt** [comment] 2023-08-20 22:30
@rophel 

> Issue 4 refuses to download, downloaded manually from GetComics and moved to directory.

Doing a (manual) search for issue 4 specifically makes it download it. 

> None of them are detected as completed, it thinks there are no issues in that volume no matter how many times I rescan.

For me it detects it just fine (files are faked, but that doesn't matter):

![image](https://github.com/Casvt/Kapowarr/assets/88994465/0ff94fa0-cb20-4216-ab77-0ac0a6f1ba71)
![image](https://github.com/Casvt/Kapowarr/assets/88994465/0dc7b2fa-29a6-4260-9723-e9b4979037fc)

---------------------

@winterborn 

I tried to reproduce, but it's working fine for me:

![image](https://github.com/Casvt/Kapowarr/assets/88994465/f5554a55-1448-4e69-8fc5-c897547699fd)
![image](https://github.com/Casvt/Kapowarr/assets/88994465/2a9fae75-96f0-4089-9a5c-a7ee181dc0e3)

**Comment by Casvt** [comment] 2023-08-21 12:42
@quentinhill 

> As for the Elvira one-shot, I tried changing the file name to TPB, and it still wasn't found. If support for one-shots isn't ready, that's cool. At least I know it's operating as expected.

I added support for one-shots. It will be included in the next release.

**Comment by Casvt** [comment] 2023-08-30 21:27
Because either it's fixed or I can't reproduce, I'll close the issue for now. If problems persist after upgrading to the next release (which will come out in a few days), we can re-open this.

**Closed by Casvt** 2023-08-30 21:27 UTC
Labels: bug
