### ISSUE TITLE
[Feature] Official Build Script

### ISSUE THREAD

**Issue by DocDrydenn** [Casvt/Kapowarr#86] opened 2023-08-16 01:03 UTC
**Is your feature request related to a problem? Please describe.**
Non-Docker Support?

**Describe the solution you'd like**
An official non-Docker set of build instructions.

**Additional context**
I've been migrating away from Docker and pushing more into the Proxmox LXC world. Would love to get this moved into a LXC as well.

Bonus: This would allow #tteck to create a Kapowarr script to add to his awesome Proxmox scripts repo.
-[tteck/Proxmox](https://github.com/tteck/Proxmox)
-[http://helper-scripts.com/](http://helper-scripts.com/)

**Comment by Casvt** [comment] 2023-08-20 21:15
Duplicate of #57

**Closed by Casvt** 2023-08-20 21:15 UTC
Labels: enhancement
